import * as THREE from 'three';

const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const mobile=matchMedia('(max-width:800px)').matches;
const lowPower=(navigator.hardwareConcurrency||8)<=4 || (navigator.deviceMemory||8)<=4;

function preload(){return new Promise(resolve=>{const wrap=$('.preloader'),num=$('.preloader span');if(sessionStorage.getItem('p188_seen')||reduced){wrap.style.display='none';resolve();return}let start=performance.now();const finish=()=>{num.textContent='188';num.classList.add('spark');sessionStorage.setItem('p188_seen','1');setTimeout(()=>{if(window.gsap)gsap.to(wrap,{opacity:0,duration:.4,onComplete:()=>{wrap.remove();resolve()}});else{wrap.remove();resolve()}},1000)};const tick=now=>{const p=Math.min(1,(now-start)/5000);num.textContent=Math.min(188,Math.floor(189*p));if(p<1)requestAnimationFrame(tick);else finish()};requestAnimationFrame(tick)})}

function sample188(count){const c=document.createElement('canvas');c.width=900;c.height=420;const x=c.getContext('2d');x.fillStyle='#fff';x.font='700 330px Marcellus,serif';x.textAlign='center';x.textBaseline='middle';x.fillText('188',450,215);const data=x.getImageData(0,0,c.width,c.height).data,pts=[];for(let yy=2;yy<c.height;yy+=3)for(let xx=2;xx<c.width;xx+=3)if(data[(yy*c.width+xx)*4+3]>100)pts.push([xx,yy]);const out=new Float32Array(count*3);for(let i=0;i<count;i++){const p=pts[(Math.random()*pts.length)|0];out[i*3]=(p[0]-450)/42;out[i*3+1]=(210-p[1])/42;out[i*3+2]=(Math.random()-.5)*.65}return out}

function initHero3D(){const canvas=$('#hero-canvas');let renderer;try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!lowPower,powerPreference:'high-performance'})}catch(e){document.body.classList.add('webgl-fallback');return null}const count=reduced?900:mobile?(lowPower?1800:5000):(lowPower?5000:20000);renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?1:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.z=18;const target=sample188(count),pos=new Float32Array(count*3);for(let i=0;i<count;i++){if(reduced){pos[i*3]=target[i*3];pos[i*3+1]=target[i*3+1];pos[i*3+2]=target[i*3+2]}else{pos[i*3]=(Math.random()-.5)*35;pos[i*3+1]=(Math.random()-.5)*22;pos[i*3+2]=(Math.random()-.5)*18}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const mat=new THREE.PointsMaterial({color:0xe8c96a,size:mobile?.05:.038,transparent:true,opacity:.94,blending:THREE.AdditiveBlending,depthWrite:false,sizeAttenuation:true});const points=new THREE.Points(geo,mat);points.position.set(mobile?1.6:4.4,mobile?1.6:.2,0);points.scale.setScalar(mobile?.68:.82);scene.add(points);
  const dustCount=lowPower?250:800,dustPos=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){dustPos[i*3]=(Math.random()-.5)*35;dustPos[i*3+1]=(Math.random()-.5)*20;dustPos[i*3+2]=-2-Math.random()*10}const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0x8a6d1f,size:.018,transparent:true,opacity:.45,depthWrite:false}));scene.add(dust);
  const pointer=new THREE.Vector2(99,99);const setPointer=(cx,cy)=>{pointer.x=(cx/innerWidth*2-1)*12-points.position.x;pointer.y=(-(cy/innerHeight)*2+1)*7-points.position.y};addEventListener('pointermove',e=>setPointer(e.clientX,e.clientY),{passive:true});addEventListener('touchmove',e=>{if(e.touches[0])setPointer(e.touches[0].clientX,e.touches[0].clientY)},{passive:true});
  let formed=0;const start=performance.now();function frame(now){const dt=Math.min(1,(now-start)/2000);formed=reduced?1:1-Math.pow(1-dt,3);const a=geo.attributes.position.array;if(!reduced){for(let i=0;i<count;i++){const k=i*3,tx=target[k],ty=target[k+1],tz=target[k+2];let dx=a[k]-pointer.x,dy=a[k+1]-pointer.y,ds=dx*dx+dy*dy;if(ds<4.84){const f=(4.84-ds)*.026;a[k]+=dx*f;a[k+1]+=dy*f}else{a[k]+=(tx-a[k])*(.02+.06*formed);a[k+1]+=(ty-a[k+1])*(.02+.06*formed);a[k+2]+=(tz-a[k+2])*.045}}geo.attributes.position.needsUpdate=true;points.rotation.y=Math.sin(now*.00022)*.075;points.rotation.x=Math.sin(now*.00017)*.025;points.position.y=(mobile?1.6:.2)+Math.sin(now*.0003)*.035;points.position.x=(mobile?1.6:4.4)+Math.sin(now*.00018)*.025;mat.opacity=.9+Math.sin(now*.003)*.06;mat.size=(mobile?.05:.038)*(1+Math.sin(now*.0045)*.08);dust.rotation.z=now*.000008;dust.position.y=Math.sin(now*.00012)*.12}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
  addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?1:1.5))});return{count}
}

function initMotion(){if(!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);if(window.Lenis&&!reduced){const lenis=new Lenis({duration:1.05,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}gsap.set('.hero h1 i',{yPercent:110});gsap.to('.hero h1 i',{yPercent:0,duration:.9,stagger:.12,ease:'power4.out',delay:.15});$$('.reveal').forEach(el=>gsap.to(el,{y:0,opacity:1,duration:.8,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));$$('.system-card').forEach((el,i)=>gsap.to(el,{y:0,opacity:1,duration:.8,delay:(i%3)*.08,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 90%',once:true}}));$$('[data-count]').forEach(el=>{const end=+el.dataset.count,obj={v:0};gsap.to(obj,{v:end,duration:1.6,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 85%',once:true},onUpdate:()=>el.textContent=end%1?obj.v.toFixed(1):Math.round(obj.v)})});gsap.to('.graph',{strokeDashoffset:0,duration:2,ease:'power2.out',scrollTrigger:{trigger:'.chart',start:'top 75%',once:true}});gsap.to('.performance-number',{xPercent:-12,ease:'none',scrollTrigger:{trigger:'.performance',start:'top bottom',end:'bottom top',scrub:1}})}

function initUI(){addEventListener('scroll',()=>$('.nav').classList.toggle('scrolled',scrollY>30),{passive:true});$('.menu-btn')?.addEventListener('click',()=>$('.nav').classList.toggle('open'));$$('.nav nav a').forEach(a=>a.addEventListener('click',()=>$('.nav').classList.remove('open')));if(!mobile){const dot=$('.cursor-dot'),ring=$('.cursor-ring');let mx=0,my=0,rx=0,ry=0;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;dot.style.transform=`translate(${mx-3}px,${my-3}px)`});(function follow(){rx+=(mx-rx)*.15;ry+=(my-ry)*.15;ring.style.transform=`translate(${rx-12}px,${ry-12}px)`;requestAnimationFrame(follow)})();$$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('hover'))})}$$('.magnetic').forEach(el=>{if(mobile)return;el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});$$('.tilt').forEach(el=>{if(mobile||reduced)return;el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(800px) rotateX(${-y*8}deg) rotateY(${x*8}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}

function initCTA(){const c=$('#cta-canvas'),x=c.getContext('2d');let pts=[];function resize(){c.width=innerWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:mobile?70:180},()=>({x:Math.random()*c.clientWidth,y:Math.random()*c.clientHeight,v:.2+Math.random()*.45}))}resize();addEventListener('resize',resize);function draw(){x.clearRect(0,0,c.clientWidth,c.clientHeight);const tx=c.clientWidth/2,ty=c.clientHeight*.68;for(const p of pts){p.x+=(tx-p.x)*.00045*p.v;p.y+=(ty-p.y)*.00045*p.v;if(Math.hypot(p.x-tx,p.y-ty)<35){p.x=Math.random()*c.clientWidth;p.y=Math.random()*c.clientHeight}x.fillStyle='rgba(201,162,39,.45)';x.fillRect(p.x,p.y,1.2,1.2)}requestAnimationFrame(draw)}draw()}

addEventListener('DOMContentLoaded',async()=>{initUI();initCTA();await preload();const hero=initHero3D();initMotion();document.body.classList.add('ready');window.__V11_READY__=true;window.__PARTICLE_COUNT__=hero?.count||0});
